### ISSUE TITLE
please credit lax1dude

### ISSUE THREAD

**Issue by OhNoItzBuster** [TheGuy888/EvenBetterThanMinekhan#1]
and ayunami2000

**Comment by TheGuy888** [comment]
Despite your completely understandable intentions, I can't help but imagine you as the kid who reminds the teacher he didn't give out homework. Probably because I'm lazy and you gave me extra work on at 3:42 AM on a saturday.

Anyway, I did what you said, and credited the creators in the repo description, and in the opening loading screen of the game.

Sorry for being rude

**Comment by OhNoItzBuster** [comment]
it's k
